<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-07-07T17:08:28 IST" name="Default suite" finished-at="2025-07-07T17:08:47 IST" duration-ms="19121">
    <groups>
    </groups>
    <test started-at="2025-07-07T17:08:28 IST" name="Default test" finished-at="2025-07-07T17:08:47 IST" duration-ms="19121">
      <class name="testcases.res">
        <test-method is-config="true" signature="setUp(java.lang.reflect.Method)[pri:0, instance:testcases.res@404bbcbd]" started-at="2025-07-07T17:08:28 IST" name="setUp" finished-at="2025-07-07T17:08:34 IST" duration-ms="5997" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testcases.res.uploadResumeToNaukri() throws java.lang.InterruptedException,java.net.URISyntaxException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="uploadResumeToNaukri()[pri:0, instance:testcases.res@404bbcbd]" started-at="2025-07-07T17:08:34 IST" name="uploadResumeToNaukri" finished-at="2025-07-07T17:08:46 IST" duration-ms="12285" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Resume file not found in test resources.]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Resume file not found in test resources.
at testcases.res.uploadResumeToNaukri(res.java:87)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- uploadResumeToNaukri -->
        <test-method is-config="true" signature="tearDown(java.lang.reflect.Method)[pri:0, instance:testcases.res@404bbcbd]" started-at="2025-07-07T17:08:47 IST" name="tearDown" finished-at="2025-07-07T17:08:47 IST" duration-ms="415" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[public void testcases.res.uploadResumeToNaukri() throws java.lang.InterruptedException,java.net.URISyntaxException]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcases.res -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
